# Generated by Django 4.1.7 on 2023-06-13 08:26

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="rol",
            field=models.CharField(
                default="comprador",
                max_length=15,
                verbose_name=django.contrib.auth.models.User,
            ),
        ),
    ]
