# Generated by Django 4.1.7 on 2023-05-30 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="date",
            field=models.DateField(
                default=datetime.date(2023, 5, 29), verbose_name="Fecha"
            ),
        ),
    ]
