# Generated by Django 4.1.7 on 2023-06-06 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_notifications_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="date",
            field=models.DateField(
                default=datetime.date(2023, 6, 5), verbose_name="Fecha"
            ),
        ),
    ]
