# Generated by Django 4.1.7 on 2023-05-22 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Name",
                    models.CharField(
                        default="Name", max_length=20, verbose_name="Nombre"
                    ),
                ),
                (
                    "Price",
                    models.FloatField(default=0, verbose_name="Precio por mayoreo"),
                ),
                (
                    "Marca",
                    models.CharField(
                        default="Marca", max_length=20, verbose_name="Marca"
                    ),
                ),
                (
                    "Description",
                    models.CharField(
                        default="clasificación",
                        max_length=50,
                        verbose_name="Clasificación",
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(default=0, verbose_name="Cantidad Disponible"),
                ),
                (
                    "photoPath",
                    models.CharField(
                        default="", max_length=50, verbose_name="Ruta de foto"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.providers",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Catálogo",
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bought", models.BooleanField(default=False, verbose_name="Comprado")),
                ("quantity", models.IntegerField(default=1, verbose_name="Cantidad")),
                (
                    "id_convenience_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.conveniencestore",
                        verbose_name="Id de comprador",
                    ),
                ),
                (
                    "id_producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                        verbose_name="Id de producto",
                    ),
                ),
                (
                    "id_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.providers",
                        verbose_name="id de Vendedor",
                    ),
                ),
            ],
        ),
    ]
