# Generated by Django 4.1.7 on 2023-06-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="Marca",
            new_name="brand",
        ),
        migrations.RenameField(
            model_name="products",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="products",
            old_name="Price",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="products",
            name="Description",
        ),
        migrations.AddField(
            model_name="cart",
            name="description",
            field=models.CharField(
                default="Descripción", max_length=50, verbose_name="Descripción"
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="photoPath",
            field=models.ImageField(upload_to="static/"),
        ),
        migrations.AddField(
            model_name="products",
            name="description",
            field=models.CharField(
                default="descripción", max_length=50, verbose_name="Descripción"
            ),
        ),
    ]
