# Generated by Django 4.1.7 on 2023-06-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_marca_products_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="photoPath",
            field=models.ImageField(blank=True, null=True, upload_to="static/"),
        ),
        migrations.AlterField(
            model_name="products",
            name="photoPath",
            field=models.ImageField(blank=True, null=True, upload_to="static/"),
        ),
    ]
