# Generated by Django 4.1.7 on 2023-06-06 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_cart_photopath_alter_products_photopath"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="description",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="id_provider",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="photoPath",
        ),
    ]
